spring.datasource.url=jdbc:postgresql://localhost:5433/panini_album
spring.datasource.username=root
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=none

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml